### ISSUE TITLE
worker on parent dead

### ISSUE THREAD

**Issue by landsman** [SkyLandTW/clevo-indicator#16]
Hi,

i try install it but I have problem with #9 and after them i try run it ($ sudo bin/clevo-indicator) but returns:

worker on parent death
worker quit

**Comment by sourcekick** [comment]
This I have too, but only if I run the command as sudo.

**Comment by aisven** [comment]
`chmod u+s clevo-indicator` solves this problem.

The command needs to have setuid=root as mentioned in detail in the README.
