### ISSUE TITLE
Keyboard issue

### ISSUE THREAD

**Issue by roncapat** [SkyLandTW/clevo-indicator#18]
Clevo W230ST - Ubuntu 16.04 - Some keys aren't detected while typing. It occurs especially when AUTO mode is enabled. More the CPU load, more the trouble. Maybe reading temps interfers with keyboard interrupts?

**Comment by GuilloOme** [comment]
I had this problem too (same laptop). I fix this issue in my fork… This was because of the refresh delay to short.

**Comment by roncapat** [comment]
Solution found (see above).

**Comment by phiresky** [comment]
Same issue here. @SkyLandTW @AqD  can you please merge that?

**Comment by junocomp** [comment]
@GuilloOme which commit is the one that changes the refresh delay?

**Comment by GuilloOme** [comment]
@giovannicaligaris, [here](https://github.com/GuilloOme/clevo-indicator/commit/5a6e040ed36c69ad1372954cffbf6624e35b2bf0)
